## Arithmetic Operation in Numpy Array 

In [1]:
import numpy as np

In [2]:
var = np.array([1,2,3,4])
varadd = var + 3
varsub = var - 3
varmul = var * 3
vardiv = var * 4
varmod = var % 2

print(varadd)
print(varsub)
print(varmul)
print(vardiv)
print(varmod)

[4 5 6 7]
[-2 -1  0  1]
[ 3  6  9 12]
[ 4  8 12 16]
[1 0 1 0]


In [3]:
var1= np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

varadd = var1 + var2
print(varadd)

[2 4 6 8]


In [4]:
var1= np.array([1,2,3,4])
var2 = np.array([1,2,3,4])

varadd = np.add(var1,var2)
print(varadd)

[2 4 6 8]


function for arithmetic :--

| Function            | Description                      | Example                 |
| ------------------- | -------------------------------- | ----------------------- |
| `np.add()`          | Adds array elements              | `np.add(a, b)`          |
| `np.subtract()`     | Subtracts array elements         | `np.subtract(a, b)`     |
| `np.multiply()`     | Multiplies array elements        | `np.multiply(a, b)`     |
| `np.divide()`       | Divides array elements           | `np.divide(a, b)`       |
| `np.floor_divide()` | Returns quotient without decimal | `np.floor_divide(a, b)` |
| `np.mod()`          | Returns remainder                | `np.mod(a, b)`          |
| `np.power()`        | Raises elements to a power       | `np.power(a, b)`        |
| `np.remainder()`    | Returns division remainder       | `np.remainder(a, b)`    |
| `np.absolute()`     | Returns absolute value           | `np.absolute(a)`        |
| `np.sqrt()`         | Returns square root              | `np.sqrt(a)`            |


### 2D ARRAY :-

In [5]:
var21 = np.array([[1,2,3,4],[1,2,3,4]])
var22 = np.array([[1,2,3,4],[1,2,3,4]])

varadd = np.add(var21,var22)
print(varadd)

[[2 4 6 8]
 [2 4 6 8]]


Numpy Common Mathematic Function :-
| Function        | Description                              |
| --------------- | ---------------------------------------- |
| `np.min(x)`     | Array ka smallest value return karta hai |
| `np.max(x)`     | Array ka largest value return karta hai  |
| `np.sum(x)`     | Sabhi elements ka sum return karta hai   |
| `np.mean(x)`    | Average (mean) return karta hai          |
| `np.median(x)`  | Median value return karta hai            |
| `np.std(x)`     | Standard deviation return karta hai      |
| `np.var(x)`     | Variance return karta hai                |
| `np.argmin(x)`  | Minimum value ka index return karta hai  |
| `np.argmax(x)`  | Maximum value ka index return karta hai  |
| `np.sqrt(x)`    | Square root return karta hai             |
| `np.cumsum(x)`  | Cumulative sum return karta hai          |
| `np.cumprod(x)` | Cumulative product return karta hai      |


In [6]:
var = np.array([2,3,4,3,5,6,3])

print("min :", np.min(var), np.argmin(var))
print("max :", np.max(var), np.argmax(var))
print("sqrt :",np.sqrt(var))

min : 2 0
max : 6 5
sqrt : [1.41421356 1.73205081 2.         1.73205081 2.23606798 2.44948974
 1.73205081]


In [7]:
var1 = np.array([[2,1,3],[9,5,6]])
print(np.min(var1,axis=0))

[2 1 3]


In [8]:
var2 = np.array([1,2,3])
print(np.sin(var2))
print(np.cos(var2))
print(np.cumsum(var2))

[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[1 3 6]
