## Numpy Array Function :-

| Function                            | Definition                                                               |
| ----------------------------------- | ------------------------------------------------------------------------ |
| **np.sort()**                       | Sorts the elements of an array in ascending order.                       |
| **np.argsort()**                    | Returns the indices that would sort the array.                           |
| **np.where()**                      | Finds the index positions of elements that satisfy a condition.          |
| **np.searchsorted()**               | Returns the position where a value should be inserted in a sorted array. |
| **Filter Array (Boolean Indexing)** | Selects and returns elements that meet a given condition.                |


In [1]:
import numpy as np

In [5]:
var = np.array([1,2,3,4,5,3,2,4,6,8,4])

x = np.where( var == 3 ) 
print(x)


(array([2, 5]),)


In [9]:
var = np.array([1,2,3,4,6,7,8])

x = np.searchsorted( var,5 ) 
print(x)


4


In [13]:
var = np.array([1,2,3,4,6,7,8,9])

x = np.searchsorted( var,5, side = "right" ) 
print(x)

4


In [17]:
# sort 
arr1 = np.array([1,2,5,2,87,4,5,3,6,9,852,22,5,7])
a = np.sort(arr1)
print(a)

[  1   2   2   3   4   5   5   5   6   7   9  22  87 852]


In [18]:
var2 = np.array(["a","s","d","f"])
print(np.sort(var2))

['a' 'd' 'f' 's']


In [20]:
arr1 = np.array([[1,2,5],[2,87,4],[5,3,6],[9,852,22],[6,5,7]])
print(arr1)
print()
print(np.sort(arr1))

[[  1   2   5]
 [  2  87   4]
 [  5   3   6]
 [  9 852  22]
 [  6   5   7]]

[[  1   2   5]
 [  2   4  87]
 [  3   5   6]
 [  9  22 852]
 [  5   6   7]]


In [22]:
# filter array 
a = np.array(["a","s","d","f"])

f = [True,False,False,True]

ar = a[f]
print(ar)

['a' 'f']


### Arithmetic function :-

| Function                | Definition                                                               |
| ----------------------- | ------------------------------------------------------------------------ |
| **np.random.shuffle()** | Randomly rearranges the elements of an array.                            |
| **np.unique()**         | Returns only the unique elements from an array.                          |
| **np.resize()**         | Changes the shape or size of an array.                                   |
| **np.flatten()**        | Converts a multi-dimensional array into a 1D array (copy).               |
| **np.ravel()**          | Converts a multi-dimensional array into a 1D array (view when possible). |


In [25]:
# to shuffle the array

var = np.array([1,2,3,4,5,6])

np.random.shuffle(var)
print(var)

[4 2 5 3 6 1]


In [27]:
# to write only unique not repetition

var1 = np.array([1,2,3,4,5,6,2,4,5,3,6,8,1])

w = np.unique(var1, return_index=True, return_counts=True)
print(w)

(array([1, 2, 3, 4, 5, 6, 8]), array([ 0,  1,  2,  3,  4,  5, 11]), array([2, 2, 2, 2, 2, 2, 1]))


In [29]:
# to resize the array
b = np.array([1,2,3,4,5,6])

q = np.resize(b,(3,2))

print(q)

[[1 2]
 [3 4]
 [5 6]]


In [30]:
b = np.array([1,2,3,4,5,6])

q = np.resize(b,(2,3))

print(q)

[[1 2 3]
 [4 5 6]]


In [33]:
# flatten - to convert into 1D array
b = np.array([1,2,3,4,5,6])

q = np.resize(b,(3,2))

print(q)

print()
print(q.flatten("C"))
print()
print(q.flatten("F"))
print()
print(q.flatten("A"))
print()
print(q.flatten("K"))

[[1 2]
 [3 4]
 [5 6]]

[1 2 3 4 5 6]

[1 3 5 2 4 6]

[1 2 3 4 5 6]

[1 2 3 4 5 6]


In [34]:
# Revel - to convert 1d array 
b = np.array([1,2,3,4,5,6])

q = np.resize(b,(3,2))

print(q)

print()
print(np.ravel(q))

[[1 2]
 [3 4]
 [5 6]]

[1 2 3 4 5 6]


Difference between flateen and Revel 

| Feature                        | `ravel()`                                | `flatten()`            |
| ------------------------------ | ---------------------------------------- | ---------------------- |
| Return Type                    | View (mostly)                            | Copy                   |
| Memory                         | Original array ki memory share karta hai | Nayi memory banata hai |
| Speed                          | Faster                                   | Thoda slower           |
| Original array change hone par | Effect pad sakta hai                     | Effect nahi padta      |


## Insert and Delete Numpy Function :-

In [48]:
var = np.array([1,2,3,4,5])
print(var)
print()
v = np.insert(var, 3, 40)
print(v)
v1 = np.append(var,22.4)
print(v1)

[1 2 3 4 5]

[ 1  2  3 40  4  5]
[ 1.   2.   3.   4.   5.  22.4]


In [ ]:
var = np.array([1,2,3,4,5])
print(var)
print()
v = np.insert(var, (3,5),40 )
print(v)

[1 2 3 4 5]

[ 1  2  3 40  4  5 40]


In [49]:
var11 = np.array([[1,2,3],[4,5,6]])
print(var11)
print()

a = np.insert(var11, 2,[8,9,6], axis =0)
print(a)
a1 = np.append(var11 , [[22,23,25]],axis =0)
print(a1)

[[1 2 3]
 [4 5 6]]

[[1 2 3]
 [4 5 6]
 [8 9 6]]
[[ 1  2  3]
 [ 4  5  6]
 [22 23 25]]


In [46]:
var11 = np.array([[1,2,3],[4,5,6]])
print(var11)
print()

a = np.insert(var11, 2,[8,9], axis =1)
print(a)

[[1 2 3]
 [4 5 6]]

[[1 2 8 3]
 [4 5 9 6]]


In [50]:
# delete

var = np.array([1,2,3,4,5])

aa = np.delete(var,4)
print(aa)

[1 2 3 4]
