## Broadcasting in Numpy :-

In [1]:
import numpy as np


In [14]:
var1 = np.array([1,2,3,4])
var2 = np.array([1,2,3,4])
print(var1 + var2)

[2 4 6 8]


In [11]:
var1 = np.array([1,2,3])
print(var1.shape)
print()
var2 = np.array([[1],[2],[3]])
print(var2)
print()
print(var2.shape)
print()
print(var2)
print()
print(var1 + var2)

(3,)

[[1]
 [2]
 [3]]

(3, 1)

[[1]
 [2]
 [3]]

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [13]:
x = np.array([[1],[2]])
print(x.shape)

y = np.array([[1,2,3],[1,2,3]])
print(y.shape)

print(x+y)

(2, 1)
(2, 3)
[[2 3 4]
 [3 4 5]]


## Indexing Numpy Arrays :-

In [16]:
var = np.array([9,8,7,6])

print(var[1])
print(var[-2])

8
7


In [17]:
var1 = np.array([[9,8,7],[4,5,6]])

print(var1)
print()
print(var1.ndim)
print()
print(var1[0,1])

[[9 8 7]
 [4 5 6]]

2

8


In [18]:
var2 = np.array([[[1,2],[1,2]]])
print(var2)
print()
print(var2.ndim)
print()
print(var2[0,1,1])


[[[1 2]
  [1 2]]]

3

2


In [ ]:
# Slicing

var1 = np.array([1,2,3,4])
print(var1)
print()

print(var1[1:5])

print(var1[1:])

print(var1[:5])
print(var1[::])

print(var1[1:8:2])


[1 2 3 4 5 6 7]

[2 3 4 5]
[2 3 4 5 6 7]
[1 2 3 4 5]
[1 2 3 4 5 6 7]
[2 4 6]


In [26]:
var1 = np.array([[1,2,3,4,5],[9,8,7,6,5],[11,12,13,14,15]])

print(var1[1,1:])

[8 7 6 5]
