## Data Types Numpy Arrays :--

| Sr.No. | Data Type    | Description                                         |
| ------ | ------------ | --------------------------------------------------- |
| 1      | `bool_`      | Boolean value store karta hai (`True` ya `False`).  |
| 2      | `int_`       | Default integer data type (normal whole numbers).   |
| 3      | `intc`       | C language ke `int` type ke saman integer.          |
| 4      | `intp`       | Indexing ke liye use hone wala integer type.        |
| 5      | `int8`       | 8-bit integer (-128 se 127 tak).                    |
| 6      | `int16`      | 16-bit integer (-32768 se 32767 tak).               |
| 7      | `int32`      | 32-bit integer (-2147483648 se 2147483647 tak).     |
| 8      | `int64`      | 64-bit integer, bahut bade numbers store karta hai. |
| 9      | `uint8`      | Unsigned 8-bit integer (0 se 255 tak).              |
| 10     | `uint16`     | Unsigned 16-bit integer (0 se 65535 tak).           |
| 11     | `uint32`     | Unsigned 32-bit integer.                            |
| 12     | `uint64`     | Unsigned 64-bit integer.                            |
| 13     | `float16`    | 16-bit decimal (floating-point) number.             |
| 14     | `float32`    | 32-bit decimal number.                              |
| 15     | `float64`    | 64-bit decimal number (default float type).         |
| 16     | `complex64`  | Complex number (real + imaginary part).             |
| 17     | `complex128` | High-precision complex number.                      |
| 18     | `str_`       | String (text) values store karta hai.               |
| 19     | `bytes_`     | Byte strings store karta hai.                       |


In [3]:
import numpy as np

In [4]:
var = np.array([1,2,3,4,35,15 ,12,13])
print("Data Type :",var.dtype)

Data Type : int64


In [5]:
var = np.array([1.1,2.2,3.2,4.2])
print("Data Type :",var.dtype)

Data Type : float64


In [8]:
var = np.array(["a","s","d","f"])
print("Data Type :",var.dtype)

Data Type : <U1


In [9]:
var = np.array(["a","s","d","f",1.1,2.2,3.2,4])
print("Data Type :",var.dtype)

Data Type : <U32


## Data Type as Function :-

list of characters that are used to present dtype in numpy

i → Integer


b → Boolean


u → Unsigned Integer


f → Float


c → Complex Float


m → Timedelta


M → Datetime


O → Object


S → String


U → Unicode String


V → Void (Fixed Chunk of Memory for Other Types)

In [13]:
x = np.array([1,2,3,4] , dtype = np.int8)
print("Data Type :",x.dtype)

Data Type : int8


In [15]:
x1 = np.array([1,2,3,4] , dtype = "f")
print("Data Type :",x1.dtype) 

Data Type : float32


In [18]:
x2 = np.array([1,2,3,4] )

new = np.float32(x2)
new_one = np.int_(x2)
print("Data Type :",x2.dtype) 
print("Data Type :",new.dtype)
print("Data Type :",new_one.dtype)
print(x2)
print(new)
print(new_one)

Data Type : int64
Data Type : float32
Data Type : int64
[1 2 3 4]
[1. 2. 3. 4.]
[1 2 3 4]


In [19]:
x3 = np.array([1,2,3,4])

new_1 = x3.astype(float)
print(x3)
print(new_1)

[1 2 3 4]
[1. 2. 3. 4.]
