## Iterating in Numpy :-

In [1]:
import numpy as np

In [2]:
var = np.array([9,8,7,6,5,4])
print(var)
print()
for i in var: 
    print(i)

[9 8 7 6 5 4]

9
8
7
6
5
4


In [6]:
var1 = np.array([[1,2,3,4],[1,2,3,4]])
print(var1)
print()

for j in var1:
    print(j)
    
print()
for k in var1:
    for l in k:
        print(l)

[[1 2 3 4]
 [1 2 3 4]]

[1 2 3 4]
[1 2 3 4]

1
2
3
4
1
2
3
4


In [12]:
var3 = np.array([[[9,8,7,6],[1,2,3,4]]])
print(var3)
print()
print(var3.ndim)
print()
for i in var3:
    for j in i:
        for k in j:
            print(k)

[[[9 8 7 6]
  [1 2 3 4]]]

3

9
8
7
6
1
2
3
4


In [2]:
var3 = np.array([[[9,8,7,6],[1,2,3,4]]])
print(var3)
print()
print(var3.ndim)
print()

for i in np.nditer(var3,flags = ['buffered'], op_dtypes = ["S"]):
    print(i)

[[[9 8 7 6]
  [1 2 3 4]]]

3

np.bytes_(b'9')
np.bytes_(b'8')
np.bytes_(b'7')
np.bytes_(b'6')
np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')


In [3]:
var3 = np.array([[[9,8,7,6],[1,2,3,4]]])
print(var3)
print()
print(var3.ndim)
print()

for i in np.nditer(var3):
    print(i)

[[[9 8 7 6]
  [1 2 3 4]]]

3

9
8
7
6
1
2
3
4


In [4]:
var3 = np.array([[[9,8,7,6],[1,2,3,4]]])
print(var3)
print()
print(var3.ndim)
print()

for i,d in np.ndenumerate(var3):
    print(i,d)

[[[9 8 7 6]
  [1 2 3 4]]]

3

(0, 0, 0) 9
(0, 0, 1) 8
(0, 0, 2) 7
(0, 0, 3) 6
(0, 1, 0) 1
(0, 1, 1) 2
(0, 1, 2) 3
(0, 1, 3) 4


## Copy vs Views Numpy Python Array :-

In [4]:
var = np.array([1,2,3,4])

co =  var.copy()

var[1]  = 40
print("var :",var)
print("copy :",co)



var : [ 1 40  3  4]
copy : [1 2 3 4]


In [5]:
x = np.array([9,8,7,6,5])

xi = x.view()
x[1] = 40
print("x :",x)
print("view :",xi)

x : [ 9 40  7  6  5]
view : [ 9 40  7  6  5]


### Difference between Copy and View :-

| Feature            | `copy()`                                 | `view()`                        |
| ------------------ | ---------------------------------------- | ------------------------------- |
| Memory             | Creates a new memory location            | Shares the same memory location |
| Data Change Effect | Changes do **not** affect original array | Changes affect original array   |
| Speed              | Slower (copies data)                     | Faster (no data copy)           |
| Storage            | Uses extra memory                        | Uses less memory                |
| Object             | Independent array                        | Reference of original array     |
| Syntax             | `arr.copy()`                             | `arr.view()`                    |


## Join and Split function Numpy Array :-

##### join() :- Used to combine two or more arrays into a single array.
##### split() :- Used to divide a single array into multiple smaller arrays.

In [ ]:
# to add two array
var = np.array([1,2,3,4,5])
var1 = np.array([6,7,8,9])

ar = np.concatenate((var,var1))
print(ar)

[1 2 3 4 5 6 7 8 9]


In [9]:
# to add 2D array 
vr = np.array([[1,2],[3,4]])
vr1 = np.array([[6,7],[8,9]])

ar_new = np.concatenate((vr,vr1),axis = 0)
print(vr)
print()
print(vr1)
print()
print(ar_new)

[[1 2]
 [3 4]]

[[6 7]
 [8 9]]

[[1 2]
 [3 4]
 [6 7]
 [8 9]]


In [10]:
vr = np.array([[1,2],[3,4]])
vr1 = np.array([[6,7],[8,9]])

ar_new = np.concatenate((vr,vr1),axis = 1)
print(vr)
print()
print(vr1)
print()
print(ar_new)

[[1 2]
 [3 4]]

[[6 7]
 [8 9]]

[[1 2 6 7]
 [3 4 8 9]]


In [15]:
vr_1 = np.array([[1,2,3,4]])
vr_2 = np.array([[6,7,8,9]])

a_new = np.stack((vr_1,vr_2),axis = 1)

print(a_new)

[[[1 2 3 4]
  [6 7 8 9]]]


In [16]:
vr_1 = np.array([[1,2,3,4]])
vr_2 = np.array([[6,7,8,9]])

a_new = np.hstack((vr_1,vr_2))

print(a_new)

[[1 2 3 4 6 7 8 9]]


In [17]:
vr_1 = np.array([[1,2,3,4]])
vr_2 = np.array([[6,7,8,9]])

a_new = np.vstack((vr_1,vr_2))

print(a_new)

[[1 2 3 4]
 [6 7 8 9]]


In [18]:
vr_1 = np.array([[1,2,3,4]])
vr_2 = np.array([[6,7,8,9]])

a_new = np.dstack((vr_1,vr_2))

print(a_new)

[[[1 6]
  [2 7]
  [3 8]
  [4 9]]]


In [20]:
# split 
varr = np.array([1,2,3,4])
print(varr)

ar = np.array_split(varr,3)
print()
print(ar)

[1 2 3 4]

[array([1, 2]), array([3]), array([4])]


In [28]:
vara = np.array([[1,2],[3,4],[5,6]])
print(vara)

ar = np.array_split(vara,3)
ar_n = np.array_split(vara,3,axis=1)
print()
print(ar)
print()
print(ar_n)

[[1 2]
 [3 4]
 [5 6]]

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]

[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]]), array([], shape=(3, 0), dtype=int64)]
