## Concept of Matix in Numpy Array :-

In [1]:
import numpy as np 

In [3]:
var = np.matrix([[1,2,3],[4,5,6],[7,8,9]])

print(var)
print(type(var))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.matrix'>


In [5]:
var1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(var1)
print(type(var1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [6]:
var1 = np.array([[1,2],[4,5]])
var2 = np.array([[1,2],[4,5]])

print(var1 + var2)

[[ 2  4]
 [ 8 10]]


In [8]:
var1 = np.array([[1,2],[4,5]])
var2 = np.array([[1,2],[4,5]])

print(var1 * var2)
print()
print(var1.dot(var2))


[[ 1  4]
 [16 25]]

[[ 9 12]
 [24 33]]


### Function in matix :-

| Function                   | Description                                       |
| -------------------------- | ------------------------------------------------- |
| `np.transpose()`           | Converts rows into columns and columns into rows. |
| `np.swapaxes()`            | Swaps two specified axes of an array.             |
| `np.linalg.inv()`          | Returns the inverse of a square matrix.           |
| `np.linalg.matrix_power()` | Raises a matrix to a given power.                 |
| `np.linalg.det()`          | Returns the determinant of a square matrix.       |


In [13]:
var = np.matrix([[1,2,3],[1,2,3]])
print(var)
print()
print(np.transpose(var))
print()
print(var.T)
print()
print(np.swapaxes(var,0,1))

[[1 2 3]
 [1 2 3]]

[[1 1]
 [2 2]
 [3 3]]

[[1 1]
 [2 2]
 [3 3]]

[[1 1]
 [2 2]
 [3 3]]


In [15]:
var2 = np.matrix([[1,2],[3,4]])
print(var2)

print(np.swapaxes(var2,0,1))

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [18]:
var2 = np.matrix([[1,2],[3,4]])
print(var2)
print()
print(np.linalg.inv(var2))

[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]


In [21]:
var4 = np.matrix([[1,2],[3,4]])
print(var4)
print()
print(np.linalg.matrix_power(var4,2))
print()
print(np.linalg.matrix_power(var4,0))
print()
print(np.linalg.matrix_power(var4,-1))
print()
print(np.linalg.matrix_power(var4,-2))
print()

[[1 2]
 [3 4]]

[[ 7 10]
 [15 22]]

[[1 0]
 [0 1]]

[[-2.   1. ]
 [ 1.5 -0.5]]

[[ 5.5  -2.5 ]
 [-3.75  1.75]]



In [22]:
var5 = np.matrix([[1,2,3],[3,4,3],[1,2,3]])
print(var4)
print()
print(np.linalg.det(var5))

[[1 2]
 [3 4]]

0.0
