In [ ]:
%timeit [j**4 for j in range(1,9)]

In [ ]:
import numpy as np

%timeit  np.arange(1,9)**4

# ARRAY

In [ ]:
import numpy as np

x = [1,2,3,4]    #list
y = np.array(x) # convert list to array , creating array
y = np.array([1,2,3,4,5] )
print(y)   
y   

print(type(y))
print(y.ndim)

In [ ]:
l = []

for i in range(1,5):
    int_1 =int(input("Enter :"))
    l.append(int_1)
    
    
print(np.array(l))

In [ ]:
# to create 2D array 

arr2 = np.array([[1,2,3,4],[1,2,3,4]])
print(arr2)
print(arr2.ndim)     # check the dimension 

In [ ]:
# to create 3D array

arr3 = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
print(arr3)
print(arr3.ndim)  # to check the dimension 

In [ ]:
# to create multi-direction array

arn = np.array([1,2,3,4], ndmin = 10)
print(arn)
print(arn.ndim)

In [ ]:
# array filled with 0's

ar_zero = np.zeros(4)
ar_zero1 = np.zeros((3,4))


print(ar_zero)
print()
print(ar_zero1)

In [ ]:
# array filled with 1's

ar_one = np.ones(4)
ar_one1 = np.ones((4,5))

print(ar_one)
print()
print(ar_one1)

In [13]:
# empty array
ar_em = np.empty(4) 
print(ar_em)            # here it uses previous memory in empty array so, we see the ouptut 


[1. 1. 1. 1.]


In [14]:
# range

ar_rn = np.arange(4)
print(ar_rn)

[0 1 2 3]


In [ ]:
# diagonal  ,  # to create identity matrix (filled with 1 diagonally)

ar_dia = np.eye(3)
print(ar_dia)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
# to create diagonally 

ar_dia = np.eye(5,5)
print(ar_dia)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [20]:
# linspace 
ar_lin = np.linspace(1,20, num = 5)
print(ar_lin)

[ 1.    5.75 10.5  15.25 20.  ]


#### create numpy arrays with random numbers

# rand()
