## Create Numpy Arrays With Random Numbers

NumPy Random Array Functions :-

rand() → Generates random decimal numbers between 0 and 1.


randn() → Generates random numbers from a normal (Gaussian) distribution.


ranf() → Generates random floating-point numbers between 0 and 1.


randint() → Generates random integers within a specified range.

In [6]:
# rand(0)
import numpy as np

var = np.random.rand(4)

print(var)

[0.88478779 0.67319182 0.59680807 0.89801904]


In [8]:
# for 2D :-

var = np.random.rand(4,4)

print(var)

[[0.58609218 0.05784575 0.59988658 0.28986425]
 [0.96905423 0.95307978 0.14235961 0.44730698]
 [0.40475855 0.43570455 0.02053711 0.13650316]
 [0.21462783 0.25635403 0.58965215 0.24255076]]


In [ ]:
# randn() :-
var2 = np.random.randn(5)
print(var2)

[-0.42326235 -0.36482986  2.1732944  -0.46196247 -0.19969728]


In [13]:
# ranf() :-
var3 = np.random.ranf(4)
print(var3)

[0.41688466 0.6714818  0.84267343 0.01739711]


In [17]:
# randint() :- 
var4 = np.random.randint(5, 20, 5)
print(var4)

[ 5  8 13 15 13]
