## Shape and Reshaping in Numpy :-

In [1]:
import numpy as np

In [2]:
# Shape :-

var = np.array([[1,2,3,4],[1,2,3,4]])

print(var)
print()
print(var.shape)

[[1 2 3 4]
 [1 2 3 4]]

(2, 4)


In [6]:
# multidirection array
var1 = np.array([1,2,3,4], ndmin = 4)
print(var1)
print()
print(var1.ndim)
print()
print(var1.shape)

[[[[1 2 3 4]]]]

4

(1, 1, 1, 4)


In [12]:
# Reshape

var2 = np.array([1,2,3,4,5,6,1,2,3])
print(var2)
print()

x = var2.reshape(3,3)

print(x)


[1 2 3 4 5 6 1 2 3]

[[1 2 3]
 [4 5 6]
 [1 2 3]]


In [15]:
var3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var3)
print()

x = var3.reshape(2,3,2)

print(x)


[ 1  2  3  4  5  6  7  8  9 10 11 12]

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [16]:
var3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var3)
print()

x1 = var3.reshape(2,3,2)

print(x)

one = x1.reshape(-1)
print(one)
print(one.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
